/* eslint-disable prettier/prettier */
export const timezones = {
  ACST: "Australian Central Standart Time (ACST) UTC+09:30",
  ACT: "Acre Time (ACT) UTC-05:00",
  ACWST: "Australian Central Western Standart Time (ACWST) UTC+08:45",
  AEST: "Australian Eastern Standard Time (AEST) UTC+10:00",
  AFT: "Afghanistan Time (AFT) UTC+04:30",
  AKST: "Alaska Standard Time (AKST) UTC-09:00",
  AMT: "Amazon Time (AMT) UTC-04:00",
  ART: "Argentina Time (ART) UTC-03:00",
  AST: "Arabia Standard Time (AST) UTC+03:00",
  AST_1: "Atlantic Standard Time (AST) UTC-04:00",
  AWST: "Australian Western Standard Time (AWST) UTC+08:00",
  AZOT: "Azores Time (AZOT) UTC-01:00",
  BOT: "Bolivia Time (BOT) UTC-04:00",
  BRT: "Brasília Time (BRT) UTC-03:00",
  BTT: "Bhutan Time (BTT) UTC+06:00",
  CAT: "Central África Time (CAT) UTC+02:00",
  CET: "Central European Time (CET) UTC+01:00",
  CHAST: "Chatham Island Standart Time (CHAST) UTC+12:45",
  CHOT: "Choibalsan Time (CHOT) UTC+08:00",
  CHUT: "Chuuk Time (CHUT) UTC+10:00",
  CKT: "Cook Island Time (CKT) UTC-10:00",
  CLT: "Chile Standard Time (CLT) UTC-04:00",
  CST: "Central Standard Time (CST) UTC-06:00",
  CST_1: "China Standard Time (CST) UTC+08:00",
  CST_2: "Cuba Standard Time (CST) UTC-05:00",
  CHST: "Chamorro Standard Time (CHST) UTC+10:00",
  EAST: "Easter Island Standard Time (EAST) UTC-06:00",
  EAT: "Eastern Africa Time (EAT) UTC+03:00",
  ECT: "Ecuador Time (ECT) UTC-05:00",
  EET: "Eastern European Time (EET) UTC+02:00",
  EST: "Eastern Standard Time (EST) UTC-05:00",
  FKST: "Falkland Islands Summer Time (FKST) UTC-03:00",
  GFT: "French Guiana Time (GFT) UTC-03:00",
  GILT: "Gilbert Island Time (GILT) UTC+12:00",
  GMT: "Greenwich Mean Time (GMT) UTC-00:00",
  GST: "Gulf Standard Time (GST) UTC+04:00",
  HKT: "Hong Kong Time (HKT) UTC+08:00",
  HST: "Hawaii Standard Time (HST) UTC-10:00",
  ICT: "Indochina Time (ICT) UTC+07:00",
  IRST: "Iran Standard Time (IRST) UTC+03:30",
  IST: "India Standard Time (IST) UTC+05:30",
  IST_1: "Israel Standard Time (IST) UTC+02:00",
  JST: "Japan Standard Time (JST) UTC+09:00",
  KOST: "Kosrae Time (KOST) UTC+11:00",
  KST: "Korea Standard Time (KST) UTC+08:30",
  LINT: "Line Inslands Time (LINT) UTC+14:00",
  MHT: "Marshall Islands Time (MHT) UTC+12:00",
  MSK: "Moscow Standard Time (MSK) UTC+03:00",
  MST: "Mountain Standard Time (MST) UTC-07:00",
  MYT: "Malaysia Time (MYT) UTC+08:00",
  NPT: "Nepal Time (NPT) UTC+05:45",
  NST: "Newfoundland Standard Time (NST) UTC-03:30",
  NUT: "Niue Time (NUT) UTC-11:00",
  NZST: "New Zealand Standard Time (NZST) UTC+12:00",
  PET: "Peru Time (PET) UTC-05:00",
  PGT: "Papua New Guinea Time (PGT) UTC+10:00",
  PHT: "Philippine Time (PHT) UTC+08:00",
  PKT: "Pakistan Standard Time (PKT) UTC+05:00",
  PONT: "Pohnpei Standard Time (PONT) UTC+11:00",
  PST: "Pacific Standard Time (PST) UTC-08:00",
  SAST: "South Africa Standard Time (SAST) UTC+02:00",
  SBT: "Solomon Islands Time (SBT) UTC+11:00",
  SGT: "Singapore Time (SGT) UTC+08:00",
  SRT: "Suriname Time (SRT) UTC-03:00",
  SST: "Samoa Standard Time (SST) UTC-11:00",
  TAHT: "Tahiti Time (TAHT) UTC-10:00",
  TLT: "East Timor Time (TLT) UTC+09:00",
  TVT: "Tuvalu Time (TVT) UTC+12:00",
  ULAT: "Ulaanbaatar Time (ULAT) UTC+08:00",
  UYT: "Uruguay Time (UYT) UTC-03:00",
  VET: "Venezuelan Standard Time (VET) UTC-04:00",
  WAT: "West Africa Time (WAT) UTC+01:00",
  WET: "Western European Time (WET) UTC-00:00",
  WIB: "Western Indonesian Time (WIB) UTC+07:00",
  WIT: "Eastern Indonesian Time (WIT) UTC+09:00",
  WITA: "Central Indonesian Time (WITA) UTC+08:00",
};
